version: 2
jobs:
  build:
    docker:
      - image: node:6
    working_directory: ~/project
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - deploy:
          name: Staging deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "staging > Deployment here ....";

              export GITFLOWPRO_DEPLOYMENT_WEBHOOK="https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwIiwiaWF0IjoxNTE1MTExNjY3LCJleHAiOjIxNDYyNjM2Njd9.rwRNAZm1IJipcrLdGKKG5LAnCKUgJGYVHLorsXwGQoU"; \
              export GITFLOWPRO_DEPLOYMENT_ENVIRONMENT="staging"; \
              export GITFLOWPRO_DEPLOYMENT_SERVICE="github"; \
              export GITFLOWPRO_DEPLOYMENT_BRANCH="${CIRCLE_BRANCH}"; \
              \
              curl \
                  -H "Content-Type: application/json" \
                  -X POST \
                  -d "{ \
                       \"service\": \"${GITFLOWPRO_DEPLOYMENT_SERVICE}\", \
                       \"branch\": \"${GITFLOWPRO_DEPLOYMENT_BRANCH}\", \
                       \"environment\": \"${GITFLOWPRO_DEPLOYMENT_ENVIRONMENT}\" \
                   }" \
                  "${GITFLOWPRO_DEPLOYMENT_WEBHOOK}" ;
            fi

      - deploy:
          name: Production deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              echo "production > Deployment here ....";

              export GITFLOWPRO_DEPLOYMENT_WEBHOOK="https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwIiwiaWF0IjoxNTE1MTExNjY3LCJleHAiOjIxNDYyNjM2Njd9.rwRNAZm1IJipcrLdGKKG5LAnCKUgJGYVHLorsXwGQoU"; \
              export GITFLOWPRO_DEPLOYMENT_ENVIRONMENT="production"; \
              export GITFLOWPRO_DEPLOYMENT_SERVICE="github"; \
              export GITFLOWPRO_DEPLOYMENT_BRANCH="${CIRCLE_BRANCH}"; \
              \
              curl \
                  -H "Content-Type: application/json" \
                  -X POST \
                  -d "{ \
                       \"service\": \"${GITFLOWPRO_DEPLOYMENT_SERVICE}\", \
                       \"branch\": \"${GITFLOWPRO_DEPLOYMENT_BRANCH}\", \
                       \"environment\": \"${GITFLOWPRO_DEPLOYMENT_ENVIRONMENT}\" \
                   }" \
                  "${GITFLOWPRO_DEPLOYMENT_WEBHOOK}" ;
            fi