version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: echo "run-tests.sh"
      - deploy:
          name: Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              GFP_DEPLOYMENT_ENVIRONMENT=staging; curl -H "Content-Type: application/json" -X POST -d "{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwIiwic2VydmljZSI6ImdpdGh1YiIsImlhdCI6MTUxNTY5ODA5OSwiZXhwIjoyMTQ2ODUwMDk5fQ.EvNP2FRm1_T7QX547qNFDOpldI_09g9rv_nAfU3i74M;
            fi

      - deploy:
          name: Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              GFP_DEPLOYMENT_ENVIRONMENT=production; curl -H "Content-Type: application/json" -X POST -d "{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwIiwic2VydmljZSI6ImdpdGh1YiIsImlhdCI6MTUxNTY5ODA5OSwiZXhwIjoyMTQ2ODUwMDk5fQ.EvNP2FRm1_T7QX547qNFDOpldI_09g9rv_nAfU3i74M;
            fi