version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: echo "run-tests.sh"
      - deploy:
          name: Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              GFP_DEPLOYMENT_ENVIRONMENT=staging; curl -H "Content-Type: application/json" -X POST -d "{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" https://h32od6i838.execute-api.us-east-1.amazonaws.com/dev/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwIiwic2VydmljZSI6ImdpdGh1YiIsImlhdCI6MTUxNTc4ODAxMCwiZXhwIjoyMTQ2OTQwMDEwfQ.ckB__wuGw9HMY8H2vaJC1kTAF2WrO_DA3fwpdbaL88Q;
            fi

      - deploy:
          name: Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              GFP_DEPLOYMENT_ENVIRONMENT=production; curl -H "Content-Type: application/json" -X POST -d "{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" https://h32od6i838.execute-api.us-east-1.amazonaws.com/dev/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwIiwic2VydmljZSI6ImdpdGh1YiIsImlhdCI6MTUxNTc4ODAxMCwiZXhwIjoyMTQ2OTQwMDEwfQ.ckB__wuGw9HMY8H2vaJC1kTAF2WrO_DA3fwpdbaL88Q;
            fi