version: 2
jobs:
  build:
    docker:
      - image: node:6
    working_directory: ~/gpf
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - deploy:
          name: Staging deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "staging > Deployment here ....";

              sleep 60

              export GITFLOWPRO_DEPLOYMENT_WEBHOOK="https://slavagitproflow.localtunnel.me/deployment/webhook"; \
              export GITFLOWPRO_DEPLOYMENT_ENVIRONMENT="staging"; \
              export GITFLOWPRO_DEPLOYMENT_SERVICE="github"; \
              export GITFLOWPRO_DEPLOYMENT_USERNAME="${CIRCLE_PROJECT_USERNAME}"; \
              export GITFLOWPRO_DEPLOYMENT_REPO="${CIRCLE_PROJECT_REPONAME}"; \
              export GITFLOWPRO_DEPLOYMENT_BRANCH="${CIRCLE_BRANCH}"; \
              \
              curl \
                  -H "Content-Type: application/json" \
                  -X POST \
                  -d "{ \
                       \"service\": \"${GITFLOWPRO_DEPLOYMENT_SERVICE}\", \
                       \"repo\": \"${GITFLOWPRO_DEPLOYMENT_REPO}\", \
                       \"username\": \"${GITFLOWPRO_DEPLOYMENT_USERNAME}\", \
                       \"branch\": \"${GITFLOWPRO_DEPLOYMENT_BRANCH}\", \
                       \"environment\": \"${GITFLOWPRO_DEPLOYMENT_ENVIRONMENT}\" \
                   }" \
                  "${GITFLOWPRO_DEPLOYMENT_WEBHOOK}" ;
            fi

      - deploy:
          name: Production deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              echo "production > Deployment here ....";

              sleep 5

              export GITFLOWPRO_DEPLOYMENT_WEBHOOK="https://slavagitproflow.localtunnel.me/deployment/webhook"; \
              export GITFLOWPRO_DEPLOYMENT_ENVIRONMENT="production"; \
              export GITFLOWPRO_DEPLOYMENT_SERVICE="github"; \
              export GITFLOWPRO_DEPLOYMENT_USERNAME="${CIRCLE_PROJECT_USERNAME}"; \
              export GITFLOWPRO_DEPLOYMENT_REPO="${CIRCLE_PROJECT_REPONAME}"; \
              export GITFLOWPRO_DEPLOYMENT_BRANCH="${CIRCLE_BRANCH}"; \
              \
              curl \
                  -H "Content-Type: application/json" \
                  -X POST \
                  -d "{ \
                       \"service\": \"${GITFLOWPRO_DEPLOYMENT_SERVICE}\", \
                       \"repo\": \"${GITFLOWPRO_DEPLOYMENT_REPO}\", \
                       \"username\": \"${GITFLOWPRO_DEPLOYMENT_USERNAME}\", \
                       \"branch\": \"${GITFLOWPRO_DEPLOYMENT_BRANCH}\", \
                       \"environment\": \"${GITFLOWPRO_DEPLOYMENT_ENVIRONMENT}\" \
                   }" \
                  "${GITFLOWPRO_DEPLOYMENT_WEBHOOK}" ;
            fi
